name: high_gang_events
description: "High Gang Events"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/logo.png
  image_dark: assets/images/logo-white.png
  android_12:
    image: assets/images/logo.png
    image_dark: assets/images/logo-white.png
    color: "#ffffff"
    color_dark: "#000000"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo-white.png
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
